import {FaceLandmarker,HandLandmarker,FilesetResolver} from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14';

const video=document.querySelector('#cam'),game=document.querySelector('#game'),start=document.querySelector('#start');
const style=document.createElement('style');
style.textContent=`#hud{position:absolute;z-index:2;inset:0;width:100%;height:100%;pointer-events:none}.choice,.listen,.exit{position:relative;overflow:hidden}.choice.hand-hover:after,.listen.hand-hover:after,.exit.hand-hover:after{content:"";position:absolute;inset:3px;border-radius:inherit;border:3px solid transparent;background:conic-gradient(#ffd161 var(--charge,0%),transparent 0) border-box;mask:linear-gradient(#000 0 0) padding-box,linear-gradient(#000 0 0);mask-composite:exclude;animation:charge .65s linear forwards}@keyframes charge{to{--charge:100%}}`;
document.head.append(style);
const c=document.createElement('canvas');c.id='hud';game.append(c);const x=c.getContext('2d');let face,hand,last=0,ready=false;
function resize(){c.width=innerWidth;c.height=innerHeight}addEventListener('resize',resize);resize();
async function boot(){if(ready||!video.srcObject)return;try{const f=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.14/wasm');const model='https://storage.googleapis.com/mediapipe-models/';face=await FaceLandmarker.createFromOptions(f,{baseOptions:{modelAssetPath:model+'face_landmarker/face_landmarker/float16/1/face_landmarker.task'},runningMode:'VIDEO',numFaces:1});hand=await HandLandmarker.createFromOptions(f,{baseOptions:{modelAssetPath:model+'hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task'},runningMode:'VIDEO',numHands:1});ready=true;requestAnimationFrame(draw)}catch(e){console.warn('HUD unavailable',e)}}
start.addEventListener('click',()=>setTimeout(boot,900));
function p(a){return[(1-a.x)*c.width,a.y*c.height]}
function drawMask(l){if(!l)return;const [lx,ly]=p(l[33]),[rx,ry]=p(l[263]),[chinX,chinY]=p(l[152]);const w=Math.abs(rx-lx)*2.4,h=(chinY-Math.min(ly,ry))*1.8,cx=(lx+rx)/2,cy=(ly+ry)/2;x.save();x.translate(cx,cy);x.fillStyle='rgba(170,32,35,.42)';x.strokeStyle='#ffd161';x.lineWidth=3;x.beginPath();x.moveTo(-w*.54,-h*.35);x.lineTo(-w*.42,h*.48);x.lineTo(0,h*.68);x.lineTo(w*.42,h*.48);x.lineTo(w*.54,-h*.35);x.lineTo(w*.25,-h*.6);x.lineTo(0,-h*.47);x.lineTo(-w*.25,-h*.6);x.closePath();x.fill();x.stroke();x.fillStyle='rgba(125,225,255,.72)';for(const s of[-1,1]){x.beginPath();x.moveTo(s*w*.43,-h*.18);x.lineTo(s*w*.07,-h*.06);x.lineTo(s*w*.24,h*.12);x.closePath();x.fill()}x.restore()}
function drawHand(l){if(!l)return;const links=[[0,1],[1,2],[2,3],[3,4],[0,5],[5,6],[6,7],[7,8],[0,9],[9,10],[10,11],[11,12],[0,13],[13,14],[14,15],[15,16],[0,17],[17,18],[18,19],[19,20],[5,9],[9,13],[13,17]];x.strokeStyle='rgba(112,226,255,.95)';x.lineWidth=3;links.forEach(([a,b])=>{let A=p(l[a]),B=p(l[b]);x.beginPath();x.moveTo(...A);x.lineTo(...B);x.stroke()});l.forEach((q,i)=>{let[a,b]=p(q);x.fillStyle=i===8?'#ffd161':'#72e3ff';x.beginPath();x.arc(a,b,i===8?10:4,0,7);x.fill()})}
function draw(t){requestAnimationFrame(draw);if(!ready||video.readyState<2||t-last<100)return;last=t;x.clearRect(0,0,c.width,c.height);const fr=face.detectForVideo(video,t),hr=hand.detectForVideo(video,t);drawMask(fr.faceLandmarks?.[0]);drawHand(hr.landmarks?.[0])}
